In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from power_systems_ops.read import login, read_tables, navigate

In [3]:
email = "coned@colorado.edu"
password = "2025NYTeam"
driver = login(email, password)

In [4]:
tables = read_tables(driver)

In [8]:
from selenium.webdriver.common.by import By

In [5]:
for k, table in tables.items():
    print(k)
    print(table)

dispatch
                Type Capacity (MW) Reliability (%) Efficiency (%)  \
Name
e1           nuclear        800.00            93.7          33.53
e2        powderCoal        700.00            95.8          40.19
e4              wind        150.00            95.6            N/A
e5    naturalgasCCGT        300.00            92.0          51.06
e7    naturalgasOCGT         50.00            92.9          36.08
e9             solar         20.00            93.6           0.00
e10          biomass         90.00             N/A          40.59
e3              wind         50.00            95.8            N/A
e6    naturalgasCCGT        600.00            94.5          53.99
e8    naturalgasOCGT         50.00             N/A          37.40

     Loan payment (M€/year) Remaining payments (years)  \
Name
e1                    308.1                         19
e2                     65.5                         19
e4                     30.7                         14
e5                     20.6                         14
e7                      3.4                          9
e9                      1.4                         14
e10                     8.8                         20
e3                      9.9                         14
e6                     38.5                         14
e8                      3.2                          9

     Fixed O&M costs (M€/year)              Status First round active Priority
Name
e1                        91.8           available                 -9        1
e2                        85.6           available                  0        2
e4                         7.1           available                 -1        3
e5                        20.3           available                -13        4
e7                         1.3           available                -11        5
e9                         0.4           available                 -3        6
e10                        N/A  under construction                  2        7
e3                         2.4           available                  0        8
e6                        38.7           available                 -6        9
e8                         1.3      in maintenance                 -5       10
last_generation
                 Type Installed capacity (MW) Available capacity (MW)  \
Plant
e1            nuclear                  800.00                  800.00
e2         powderCoal                  700.00                  700.00
e4               wind                  150.00                   91.50
e5     naturalgasCCGT                  300.00                  300.00
e7     naturalgasOCGT                   50.00                   50.00
e9              solar                   20.00                    9.20
e10           biomass                   90.00                     N/A
e3               wind                   50.00                   30.50
e6     naturalgasCCGT                  600.00                  600.00
e8     naturalgasOCGT                   50.00                     N/A

      Fuel consumption (units of fuel) -- Off-peak  \
Plant
e1                                             0.0
e2                                             0.0
e4                                             0.0
e5                                             0.0
e7                                             0.0
e9                                             0.0
e10                                            0.0
e3                                             0.0
e6                                             0.0
e8                                             0.0

      Fuel consumption (units of fuel) -- Shoulder  \
Plant
e1                                             0.0
e2                                             0.0
e4                                             0.0
e5                                             0.0
e7                                             0.0
e9                                             0.0
e10                                            0.0
e3                                             0.0
e6                                             0.0
e8                                             0.0

      Fuel consumption (units of fuel) -- Peak
Plant
e1                                         0.0
e2                                         0.0
e4                                         0.0
e5                                         0.0
e7                                         0.0
e9                                         0.0
e10                                        0.0
e3                                         0.0
e6                                         0.0
e8                                         0.0
availability
      Round -- 1
Plant
e1
e2
e4
e5
e7
e9
e10            X
e3
e6
e8             X
overview
                Company            Type Capacity (MW) Round active  \
Plant name
a3                 Xcel            wind        250.00            0
b4          Duke Energy            wind        200.00            0
c4                  AES            wind        150.00            0
d5             Dominion            wind         50.00            0
e2                ConEd      powderCoal        700.00            0
e3                ConEd            wind         50.00            0
a10                Xcel         biomass        100.00           -1
d9             Dominion           solar         20.00           -1
e4                ConEd            wind        150.00           -1
c9                  AES           solar         20.00           -2
c2                  AES      powderCoal        600.00           -3
d4             Dominion            wind         50.00           -3
e9                ConEd           solar         20.00           -3
d10            Dominion         biomass        100.00           -3
b6          Duke Energy  naturalgasCCGT        500.00           -4
c5                  AES            wind        100.00           -4
c8                  AES  naturalgasOCGT         50.00           -4
a7                 Xcel  naturalgasOCGT         50.00           -5
a9                 Xcel           solar         20.00           -5
c10                 AES         biomass        120.00           -5
d8             Dominion  naturalgasOCGT         50.00           -5
e8                ConEd  naturalgasOCGT         50.00           -5
a4                 Xcel            wind         50.00           -6
a8                 Xcel  naturalgasOCGT         50.00           -6
b5          Duke Energy            wind         15.00           -6
b9          Duke Energy           solar         20.00           -6
d2             Dominion      powderCoal        600.00           -6
e6                ConEd  naturalgasCCGT        600.00           -6
a2                 Xcel      powderCoal        700.00           -7
b2          Duke Energy      powderCoal        600.00           -8
d7             Dominion  naturalgasOCGT         50.00           -8
a1                 Xcel         nuclear        800.00           -9
b1          Duke Energy         nuclear        800.00           -9
c1                  AES         nuclear        800.00           -9
d1             Dominion         nuclear        800.00           -9
e1                ConEd         nuclear        800.00           -9
b8          Duke Energy  naturalgasOCGT         35.00          -10
c6                  AES  naturalgasCCGT        350.00          -10
c7                  AES  naturalgasOCGT         50.00          -10
b7          Duke Energy  naturalgasOCGT         50.00          -11
e7                ConEd  naturalgasOCGT         50.00          -11
d6             Dominion  naturalgasCCGT        500.00          -11
b3          Duke Energy      powderCoal        500.00          -13
e5                ConEd  naturalgasCCGT        300.00          -13
a5                 Xcel  naturalgasCCGT        600.00          -14
d3             Dominion      powderCoal        600.00          -14
c3                  AES      powderCoal        600.00          -16
a6                 Xcel  naturalgasCCGT        200.00          -18
b10         Duke Energy         biomass         70.00            2
e10               ConEd         biomass         90.00            2
                   None

           Round dismantled              status
Plant name
a3                                  operational
b4                                  operational
c4                                  operational
d5                                  operational
e2                                  operational
e3                                  operational
a10                                 operational
d9                                  operational
e4                                  operational
c9                                  operational
c2                                  operational
d4                                  operational
e9                                  operational
d10                                 operational
b6                                  operational
c5                                  operational
c8                                  operational
a7                                  operational
a9                                  operational
c10                                 operational
d8                                  operational
e8                                  operational
a4                                  operational
a8                                  operational
b5                                  operational
b9                                  operational
d2                                  operational
e6                                  operational
a2                                  operational
b2                                  operational
d7                                  operational
a1                                  operational
b1                                  operational
c1                                  operational
d1                                  operational
e1                                  operational
b8                                  operational
c6                                  operational
c7                                  operational
b7                                  operational
e7                                  operational
d6                                  operational
b3                                  operational
e5                                  operational
a5                                  operational
d3                                  operational
c3                                  operational
a6                                  operational
b10                          under construction
e10                          under construction
                                     dismantled
Fuel characteristics
           Renewable       Fuel unit Energy value -- (MJ/fuel unit)  \
Fuel name
coal           false             ton                        25000.0
biomass        false             ton                        15500.0
naturalgas     false              m3                         35.069
wind            true  not applicable                            0.0
nuclear        false              kg                      3888000.0
solar           true  not applicable                            0.0

           Emission factor -- (ton CO2/fuel unit)
Fuel name
coal                                         2.66
biomass                                       0.0
naturalgas                                0.00187
wind                                          0.0
nuclear                                       0.0
solar                                         0.0
Coal
      Price (€/ton)
Round
1             38.44
0             35.67
-1            29.91
-2            29.39
-3            30.26
-4            30.64
-5            30.75
Biomass
      Price (€/ton)
Round
1             41.33
0             75.92
-1            90.77
-2            85.31
-3           115.28
-4           123.74
-5           128.85
Natural gas
      Price (€/m3)
Round
1             0.16
0             0.17
-1             0.2
-2            0.21
-3            0.23
-4            0.26
-5            0.28
Nuclear fuel
      Price (€/kg)
Round
1          1368.07
0          1373.58
-1         1376.89
-2         1383.78
-3         1407.75
-4         1411.33
-5         1413.81
Wind availability
      Wind availability (%)
Round
1                      61.0
0                      27.0
-1                     33.0
-2                     43.0
-3                     17.0
-4                     30.0
-5                     85.0
Solar
      Solar availability (%)
Round
1                       46.0
0                       41.0
-1                      14.0
-2                      23.0
-3                      27.0
-4                      37.0
-5                      28.0
Electricity demand
      Growth rate (%)
Round
1                 1.6
0                 2.1
-1                3.2
-2                2.7
-3                2.1
-4                3.2
-5                3.6

In [13]:
pp_link = driver.find_element(By.XPATH, "//a[@title='Power plants']")
pp_link.find_element(By.TAG_NAME, 'img').click()

In [22]:
for link in links:
    print(link.get_attribute('href'))
    print(link.get_attribute('title'))

https://emsg2.tbm.tudelft.nl/cu-boulder-2025/instance_select.jsp
Other instances
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/logout.jsp
Logout
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/dashboard.jsp
Dashboard
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/stocks_and_trends.jsp
Stocks & trends
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/plantsOverview.jsp
Power plants
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/plantsAuctioning.jsp
Build, decommision or trade plant
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/bank.jsp
Bank account
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/electricity_market.jsp
Electricity market
https://emsg2.tbm.tudelft.nl/cu-boulder-2025/player/balancing_market.jsp
Balancing market

Delft University of Technology and Fields of View

In [20]:
import pandas as pd

In [56]:
TABLE_NAME_TO_KEY = {
    "Power plant portfolio": "dispatch",
    "Electricity generation and fuel consumption in the past round": "last_generation",
    "Electricity production per plant": "production",
    "Power plant availability": "availability",
    "Overview of power plants": "overview"
}

INDEX_NAMES = {
    "dispatch": "Name",
    # "last_generation": "Plant",
    # "availability": "Plant",
    # "overview": "Plant name"
}

In [60]:
driver.find_element(By.TAG_NAME, "table").find_elements(By.TAG_NAME, 'th')

[<selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.267")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.269")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.271")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.188")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.63")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.64")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.65")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.277")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.66")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.67")>,
 <selenium.webdriver.remote.webelement.WebElement (session="f9623eddaa8dbefd2f2daa6657b9685c", element="f.8835B30BC8830730D0ED6E8BD6080507.d.DB579C6F2A0BCCBC3DB128ED0CAEBE64.e.68")>]

In [84]:
def filter_empty(strings):
    return [s for s in strings if s]
    
def join_2_rows(header_elem, key):
    rows = header_elem.find_elements(By.TAG_NAME, "tr")
    assert len(rows) == 2
    row1 = [h.text for h in rows[0].find_elements(By.TAG_NAME, 'th')]
    row2 = [h.text for h in rows[1].find_elements(By.TAG_NAME, 'th')]
    if key == "last_generation":
        # Extend the final column of the first row, since it pertains to each
        # of the last three columns of row2...
        
        row1 += [row1[-1], row1[-1]]
    return [' -- '.join(filter_empty([h1, h2])) for h1, h2 in zip(row1, row2)]
    
def extract_column_names(table, key):

    header_elem = table.find_element(By.TAG_NAME, "thead")
    # Add special logic for each table...
    if key in ['last_generation', 'availability']:
        return join_2_rows(header_elem, key)

    column_names = [header.text for header in header_elem.find_elements(By.TAG_NAME, "th")]

    if key == "overview":
        column_names.append("status")
    
    return column_names

def extract_rows(table, key):
    body = table.find_element(By.TAG_NAME, "tbody")
    rows = body.find_elements(By.TAG_NAME, "tr")
    if key == "overview":
        return extract_rows_overview(rows)
        
    data = []
    for row in rows:
        cells = row.find_elements(By.TAG_NAME, "td")
        row_data = [cell.text for cell in cells]
        data.append(row_data)
    return data


HEADER_TO_KEY = {
    "Operational power plants": "operational",
    "Power plants under construction": "under construction",
    "Dismantled power plants": "dismantled"
}

def extract_rows_overview(rows):
    data = []
    current_status = None
    for row in rows:
        headers = row.find_elements(By.TAG_NAME, "th")
        if headers:
            assert len(headers) == 1
            current_status = HEADER_TO_KEY[headers[0].text]
            continue
        row_data = [cell.text for cell in row.find_elements(By.TAG_NAME, "td")]
        if current_status == "under construction":
            # For some reason data in the section is missing a cell for "round dismantled".
            row_data.append('')
        row_data.append(current_status)
        data.append(row_data)
    return data
        
    
def extract_table(table, key):
    
    # Extract table headers and rows
    headers = extract_column_names(table, key)
    
    # Prepare data for DataFrame (skip the header row)
    rows = extract_rows(table, key)
    
    # Create a DataFrame
    df = pd.DataFrame(rows, columns=headers)
    if index_name is not None:
        df = df.set_index(index_name)
    return df

In [85]:
tables = {}

table_containers = driver.find_elements(By.XPATH, "//div[@class='component table left white']")

for div in table_containers:
    name = div.find_element(By.TAG_NAME, 'h4').text
    key = TABLE_NAME_TO_KEY[name]
    print(key)
    tables_found = div.find_elements(By.TAG_NAME, "table")
    if len(tables_found) > 1:
        raise ValueError("Found multiple tables within single div!!!")
    elif len(tables_found) == 1:
        index_name = INDEX_NAMES.get(key)
        df = extract_table(tables_found[0], key)
        print(df)
        tables[key] = df

dispatch
                Type Capacity (MW) Reliability (%) Efficiency (%)  \
Name
e1           nuclear        800.00            93.7          33.53
e2        powderCoal        700.00            95.8          40.19
e4              wind        150.00            95.6            N/A
e5    naturalgasCCGT        300.00            92.0          51.06
e7    naturalgasOCGT         50.00            92.9          36.08
e9             solar         20.00            93.6           0.00
e10          biomass         90.00             N/A          40.59
e3              wind         50.00            95.8            N/A
e6    naturalgasCCGT        600.00            94.5          53.99
e8    naturalgasOCGT         50.00             N/A          37.40

     Loan payment (M€/year) Remaining payments (years)  \
Name
e1                    308.1                         19
e2                     65.5                         19
e4                     30.7                         14
e5                     20.6                         14
e7                      3.4                          9
e9                      1.4                         14
e10                     8.8                         20
e3                      9.9                         14
e6                     38.5                         14
e8                      3.2                          9

     Fixed O&M costs (M€/year)              Status First round active Priority
Name
e1                        91.8           available                 -9        1
e2                        85.6           available                  0        2
e4                         7.1           available                 -1        3
e5                        20.3           available                -13        4
e7                         1.3           available                -11        5
e9                         0.4           available                 -3        6
e10                        N/A  under construction                  2        7
e3                         2.4           available                  0        8
e6                        38.7           available                 -6        9
e8                         1.3      in maintenance                 -5       10
last_generation
  Plant            Type Installed capacity (MW) Available capacity (MW)  \
0    e1         nuclear                  800.00                  800.00
1    e2      powderCoal                  700.00                  700.00
2    e4            wind                  150.00                   91.50
3    e5  naturalgasCCGT                  300.00                  300.00
4    e7  naturalgasOCGT                   50.00                   50.00
5    e9           solar                   20.00                    9.20
6   e10         biomass                   90.00                     N/A
7    e3            wind                   50.00                   30.50
8    e6  naturalgasCCGT                  600.00                  600.00
9    e8  naturalgasOCGT                   50.00                     N/A

  Fuel consumption (units of fuel) -- Off-peak  \
0                                          0.0
1                                          0.0
2                                          0.0
3                                          0.0
4                                          0.0
5                                          0.0
6                                          0.0
7                                          0.0
8                                          0.0
9                                          0.0

  Fuel consumption (units of fuel) -- Shoulder  \
0                                          0.0
1                                          0.0
2                                          0.0
3                                          0.0
4                                          0.0
5                                          0.0
6                                          0.0
7                                          0.0
8                                          0.0
9                                          0.0

  Fuel consumption (units of fuel) -- Peak
0                                      0.0
1                                      0.0
2                                      0.0
3                                      0.0
4                                      0.0
5                                      0.0
6                                      0.0
7                                      0.0
8                                      0.0
9                                      0.0
production
availability
  Plant Round -- 1
0    e1
1    e2
2    e4
3    e5
4    e7
5    e9
6   e10          X
7    e3
8    e6
9    e8          X
overview
        Company Plant name            Type Capacity (MW) Round active  \
0          Xcel         a3            wind        250.00            0
1   Duke Energy         b4            wind        200.00            0
2           AES         c4            wind        150.00            0
3      Dominion         d5            wind         50.00            0
4         ConEd         e2      powderCoal        700.00            0
5         ConEd         e3            wind         50.00            0
6          Xcel        a10         biomass        100.00           -1
7      Dominion         d9           solar         20.00           -1
8         ConEd         e4            wind        150.00           -1
9           AES         c9           solar         20.00           -2
10          AES         c2      powderCoal        600.00           -3
11     Dominion         d4            wind         50.00           -3
12        ConEd         e9           solar         20.00           -3
13     Dominion        d10         biomass        100.00           -3
14  Duke Energy         b6  naturalgasCCGT        500.00           -4
15          AES         c5            wind        100.00           -4
16          AES         c8  naturalgasOCGT         50.00           -4
17         Xcel         a7  naturalgasOCGT         50.00           -5
18         Xcel         a9           solar         20.00           -5
19          AES        c10         biomass        120.00           -5
20     Dominion         d8  naturalgasOCGT         50.00           -5
21        ConEd         e8  naturalgasOCGT         50.00           -5
22         Xcel         a4            wind         50.00           -6
23         Xcel         a8  naturalgasOCGT         50.00           -6
24  Duke Energy         b5            wind         15.00           -6
25  Duke Energy         b9           solar         20.00           -6
26     Dominion         d2      powderCoal        600.00           -6
27        ConEd         e6  naturalgasCCGT        600.00           -6
28         Xcel         a2      powderCoal        700.00           -7
29  Duke Energy         b2      powderCoal        600.00           -8
30     Dominion         d7  naturalgasOCGT         50.00           -8
31         Xcel         a1         nuclear        800.00           -9
32  Duke Energy         b1         nuclear        800.00           -9
33          AES         c1         nuclear        800.00           -9
34     Dominion         d1         nuclear        800.00           -9
35        ConEd         e1         nuclear        800.00           -9
36  Duke Energy         b8  naturalgasOCGT         35.00          -10
37          AES         c6  naturalgasCCGT        350.00          -10
38          AES         c7  naturalgasOCGT         50.00          -10
39  Duke Energy         b7  naturalgasOCGT         50.00          -11
40        ConEd         e7  naturalgasOCGT         50.00          -11
41     Dominion         d6  naturalgasCCGT        500.00          -11
42  Duke Energy         b3      powderCoal        500.00          -13
43        ConEd         e5  naturalgasCCGT        300.00          -13
44         Xcel         a5  naturalgasCCGT        600.00          -14
45     Dominion         d3      powderCoal        600.00          -14
46          AES         c3      powderCoal        600.00          -16
47         Xcel         a6  naturalgasCCGT        200.00          -18
48  Duke Energy        b10         biomass         70.00            2
49        ConEd        e10         biomass         90.00            2
50         None

   Round dismantled              status
0                           operational
1                           operational
2                           operational
3                           operational
4                           operational
5                           operational
6                           operational
7                           operational
8                           operational
9                           operational
10                          operational
11                          operational
12                          operational
13                          operational
14                          operational
15                          operational
16                          operational
17                          operational
18                          operational
19                          operational
20                          operational
21                          operational
22                          operational
23                          operational
24                          operational
25                          operational
26                          operational
27                          operational
28                          operational
29                          operational
30                          operational
31                          operational
32                          operational
33                          operational
34                          operational
35                          operational
36                          operational
37                          operational
38                          operational
39                          operational
40                          operational
41                          operational
42                          operational
43                          operational
44                          operational
45                          operational
46                          operational
47                          operational
48                   under construction
49                   under construction
50                           dismantled

In [52]:
tables['last_generation']

,Name,Type,Capacity (MW),Reliability (%),Efficiency (%),Loan payment (M€/year),Remaining payments (years),Fixed O&M costs (M€/year),Status,First round active,Priority
0,e1,nuclear,800.00,93.7,33.53,308.1,19,91.8,available,-9,1
1,e2,powderCoal,700.00,95.8,40.19,65.5,19,85.6,available,0,2
2,e4,wind,150.00,95.6,N/A,30.7,14,7.1,available,-1,3
3,e5,naturalgasCCGT,300.00,92.0,51.06,20.6,14,20.3,available,-13,4
4,e7,naturalgasOCGT,50.00,92.9,36.08,3.4,9,1.3,available,-11,5
5,e9,solar,20.00,93.6,0.00,1.4,14,0.4,available,-3,6
6,e10,biomass,90.00,N/A,40.59,8.8,20,N/A,under construction,2,7
7,e3,wind,50.00,95.8,N/A,9.9,14,2.4,available,0,8
8,e6,naturalgasCCGT,600.00,94.5,53.99,38.5,14,38.7,available,-6,9
9,e8,naturalgasOCGT,50.00,N/A,37.40,3.2,9,1.3,in maintenance,-5,10

In [ ]:
table = driver.find_element(By.XPATH, f"//table[@id='{id_}']")

In [30]:
dispatch_stack = extract_table("powerplants", "Name")

In [32]:
dispatch_stack

,Type,Capacity (MW),Reliability (%),Efficiency (%),Loan payment (M€/year),Remaining payments (years),Fixed O&M costs (M€/year),Status,First round active,Priority
Name,,,,,,,,,,
e1,nuclear,800.00,93.7,33.53,308.1,19,91.8,available,-9,1
e2,powderCoal,700.00,95.8,40.19,65.5,19,85.6,available,0,2
e4,wind,150.00,95.6,N/A,30.7,14,7.1,available,-1,3
e5,naturalgasCCGT,300.00,92.0,51.06,20.6,14,20.3,available,-13,4
e7,naturalgasOCGT,50.00,92.9,36.08,3.4,9,1.3,available,-11,5
e9,solar,20.00,93.6,0.00,1.4,14,0.4,available,-3,6
e10,biomass,90.00,N/A,40.59,8.8,20,N/A,under construction,2,7
e3,wind,50.00,95.8,N/A,9.9,14,2.4,available,0,8
e6,naturalgasCCGT,600.00,94.5,53.99,38.5,14,38.7,available,-6,9
e8,naturalgasOCGT,50.00,N/A,37.40,3.2,9,1.3,in maintenance,-5,10

In [15]:
link

''

In [14]:
dir(link)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_execute',
 '_id',
 '_parent',
 '_upload',
 'accessible_name',
 'aria_role',
 'clear',
 'click',
 'find_element',
 'find_elements',
 'get_attribute',
 'get_dom_attribute',
 'get_property',
 'id',
 'is_displayed',
 'is_enabled',
 'is_selected',
 'location',
 'location_once_scrolled_into_view',
 'parent',
 'rect',
 'screenshot',
 'screenshot_as_base64',
 'screenshot_as_png',
 'send_keys',
 'shadow_root',
 'size',
 'submit',
 'tag_name',
 'text',
 'value_of_css_property']

In [7]:
help(webdriver.Chrome)

Help on class WebDriver in module selenium.webdriver.chrome.webdriver:

class WebDriver(selenium.webdriver.chromium.webdriver.ChromiumDriver)
 |  WebDriver(options: selenium.webdriver.chrome.options.Options = None, service: selenium.webdriver.chrome.service.Service = None, keep_alive: bool = True) -> None
 |
 |  Controls the ChromeDriver and allows you to drive the browser.
 |
 |  Method resolution order:
 |      WebDriver
 |      selenium.webdriver.chromium.webdriver.ChromiumDriver
 |      selenium.webdriver.remote.webdriver.WebDriver
 |      selenium.webdriver.remote.webdriver.BaseWebDriver
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, options: selenium.webdriver.chrome.options.Options = None, service: selenium.webdriver.chrome.service.Service = None, keep_alive: bool = True) -> None
 |      Creates a new instance of the chrome driver. Starts the service and
 |      then creates new instance of chrome driver.
 |
 |      :Args:
 |       - options - this takes an instance of ChromeOptions
 |       - service - Service object for handling the browser driver if you need to pass extra details
 |       - keep_alive - Whether to configure ChromeRemoteConnection to use HTTP keep-alive.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from selenium.webdriver.chromium.webdriver.ChromiumDriver:
 |
 |  delete_network_conditions(self) -> None
 |      Resets Chromium network emulation settings.
 |
 |  execute_cdp_cmd(self, cmd: str, cmd_args: dict)
 |      Execute Chrome Devtools Protocol command and get returned result The
 |      command and command args should follow chrome devtools protocol
 |      domains/commands, refer to link
 |      https://chromedevtools.github.io/devtools-protocol/
 |
 |      :Args:
 |       - cmd: A str, command name
 |       - cmd_args: A dict, command args. empty dict {} if there is no command args
 |      :Usage:
 |          ::
 |
 |              driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': requestId})
 |      :Returns:
 |          A dict, empty dict {} if there is no result to return.
 |          For example to getResponseBody:
 |          {'base64Encoded': False, 'body': 'response body string'}
 |
 |  get_issue_message(self)
 |      :Returns: An error message when there is any issue in a Cast
 |      session.
 |
 |  get_network_conditions(self)
 |      Gets Chromium network emulation settings.
 |
 |      :Returns:
 |          A dict.
 |          For example:     {'latency': 4, 'download_throughput': 2, 'upload_throughput': 2, 'offline': False}
 |
 |  get_sinks(self) -> list
 |      :Returns: A list of sinks available for Cast.
 |
 |  launch_app(self, id)
 |      Launches Chromium app specified by id.
 |
 |  quit(self) -> None
 |      Closes the browser and shuts down the ChromiumDriver executable.
 |
 |  set_network_conditions(self, **network_conditions) -> None
 |      Sets Chromium network emulation settings.
 |
 |      :Args:
 |       - network_conditions: A dict with conditions specification.
 |
 |      :Usage:
 |          ::
 |
 |              driver.set_network_conditions(
 |                  offline=False,
 |                  latency=5,  # additional latency (ms)
 |                  download_throughput=500 * 1024,  # maximal throughput
 |                  upload_throughput=500 * 1024)  # maximal throughput
 |
 |          Note: 'throughput' can be used to set both (for download and upload).
 |
 |  set_permissions(self, name: str, value: str) -> None
 |      Sets Applicable Permission.
 |
 |      :Args:
 |       - name: The item to set the permission on.
 |       - value: The value to set on the item
 |
 |      :Usage:
 |          ::
 |
 |              driver.set_permissions('clipboard-read', 'denied')
 |
 |  set_sink_to_use(self, sink_name: str) -> dict
 |      Sets a specific sink, using its name, as a Cast session receiver
 |      target.
 |
 |      :Args:
 |       - sink_name: Name of the sink to use as the target.
 |
 |  start_desktop_mirroring(self, sink_name: str) -> dict
 |      Starts a desktop mirroring session on a specific receiver target.
 |
 |      :Args:
 |       - sink_name: Name of the sink to use as the target.
 |
 |  start_tab_mirroring(self, sink_name: str) -> dict
 |      Starts a tab mirroring session on a specific receiver target.
 |
 |      :Args:
 |       - sink_name: Name of the sink to use as the target.
 |
 |  stop_casting(self, sink_name: str) -> dict
 |      Stops the existing Cast session on a specific receiver target.
 |
 |      :Args:
 |       - sink_name: Name of the sink to stop the Cast session.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from selenium.webdriver.remote.webdriver.WebDriver:
 |
 |  __enter__(self)
 |
 |  __exit__(self, exc_type: Optional[Type[BaseException]], exc: Optional[BaseException], traceback: Optional[traceback])
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  add_cookie(self, cookie_dict) -> None
 |      Adds a cookie to your current session.
 |
 |      Parameters:
 |      ----------
 |      cookie_dict : dict
 |          - A dictionary object, with required keys - "name" and "value";
 |          - Optional keys - "path", "domain", "secure", "httpOnly", "expiry", "sameSite"
 |
 |      Examples:
 |      --------
 |      >>> driver.add_cookie({'name' : 'foo', 'value' : 'bar'})
 |      >>> driver.add_cookie({'name' : 'foo', 'value' : 'bar', 'path' : '/'})
 |      >>> driver.add_cookie({'name' : 'foo', 'value' : 'bar', 'path' : '/', 'secure' : True})
 |      >>> driver.add_cookie({'name' : 'foo', 'value' : 'bar', 'sameSite' : 'Strict'})
 |
 |  add_credential(self, credential: selenium.webdriver.common.virtual_authenticator.Credential) -> None
 |      Injects a credential into the authenticator.
 |
 |      Example:
 |      --------
 |      >>> from selenium.webdriver.common.credential import Credential
 |      >>> credential = Credential(id="user@example.com", password="aPassword")
 |      >>> driver.add_credential(credential)
 |
 |  add_virtual_authenticator(self, options: selenium.webdriver.common.virtual_authenticator.VirtualAuthenticatorOptions) -> None
 |      Adds a virtual authenticator with the given options.
 |
 |      Example:
 |      --------
 |      >>> from selenium.webdriver.common.virtual_authenticator import VirtualAuthenticatorOptions
 |      >>> options = VirtualAuthenticatorOptions(protocol="u2f", transport="usb", device_id="myDevice123")
 |      >>> driver.add_virtual_authenticator(options)
 |
 |  back(self) -> None
 |      Goes one step backward in the browser history.
 |
 |      Example:
 |      --------
 |      >>> driver.back()
 |
 |  bidi_connection(self)
 |
 |  close(self) -> None
 |      Closes the current window.
 |
 |      Example:
 |      --------
 |      >>> driver.close()
 |
 |  create_web_element(self, element_id: str) -> selenium.webdriver.remote.webelement.WebElement
 |      Creates a web element with the specified `element_id`.
 |
 |  delete_all_cookies(self) -> None
 |      Delete all cookies in the scope of the session.
 |
 |      Example:
 |      --------
 |      >>> driver.delete_all_cookies()
 |
 |  delete_cookie(self, name) -> None
 |      Deletes a single cookie with the given name.
 |
 |      Example:
 |      --------
 |      >>> driver.delete_cookie('my_cookie')
 |
 |  delete_downloadable_files(self) -> None
 |      Deletes all downloadable files.
 |
 |      Example:
 |      --------
 |      >>> driver.delete_downloadable_files()
 |
 |  download_file(self, file_name: str, target_directory: str) -> None
 |      Downloads a file with the specified file name to the target
 |      directory.
 |
 |      Parameters:
 |      ----------
 |      file_name : str
 |          - The name of the file to download.
 |
 |      target_directory : str
 |          - The path to the directory to save the downloaded file.
 |
 |      Example:
 |      --------
 |      >>> driver.download_file("example.zip", "/path/to/directory")
 |
 |  execute(self, driver_command: str, params: dict = None) -> dict
 |      Sends a command to be executed by a command.CommandExecutor.
 |
 |      Parameters:
 |      ----------
 |      driver_command : str
 |          - The name of the command to execute as a string.
 |
 |      params : dict
 |          - A dictionary of named Parameters to send with the command.
 |
 |      Returns:
 |      --------
 |        dict - The command's JSON response loaded into a dictionary object.
 |
 |  execute_async_script(self, script: str, *args)
 |      Asynchronously Executes JavaScript in the current window/frame.
 |
 |      Parameters:
 |      ----------
 |      script : str
 |          - The javascript to execute.
 |
 |      *args : tuple
 |          - Any applicable arguments for your JavaScript.
 |
 |      Example:
 |      --------
 |      >>> script = "var callback = arguments[arguments.length - 1]; "
 |      ...     "window.setTimeout(function(){ callback('timeout') }, 3000);"
 |      >>> driver.execute_async_script(script)
 |
 |  execute_script(self, script, *args)
 |      Synchronously Executes JavaScript in the current window/frame.
 |
 |      Parameters:
 |      ----------
 |      script : str
 |          - The javascript to execute.
 |
 |      *args : tuple
 |          - Any applicable arguments for your JavaScript.
 |
 |      Example:
 |      --------
 |      >>> input_id = "username"
 |      >>> input_value = "test_user"
 |      >>> driver.execute_script(
 |      ...     "document.getElementById(arguments[0]).value = arguments[1];", input_id, input_value
 |      ... )
 |
 |  fedcm_dialog(self, timeout=5, poll_frequency=0.5, ignored_exceptions=None)
 |      Waits for and returns the FedCM dialog.
 |
 |      Parameters:
 |      ----------
 |      timeout : int
 |          - How long to wait for the dialog
 |
 |      poll_frequency : floatHow
 |          - Frequently to poll
 |
 |      ignored_exceptions : Any
 |          - Exceptions to ignore while waiting
 |
 |      Returns:
 |      -------
 |          The FedCM dialog object if found
 |
 |      Raises:
 |      -------
 |          TimeoutException if dialog doesn't appear
 |          WebDriverException if FedCM not supported
 |
 |  file_detector_context(self, file_detector_class, *args, **kwargs)
 |      Overrides the current file detector (if necessary) in limited
 |      context. Ensures the original file detector is set afterwards.
 |
 |      Parameters:
 |      ----------
 |      file_detector_class : object
 |          - Class of the desired file detector. If the class is different
 |          from the current file_detector, then the class is instantiated with args and kwargs
 |          and used as a file detector during the duration of the context manager.
 |      args : tuple
 |          - Optional arguments that get passed to the file detector class during instantiation.
 |      kwargs : dict
 |          - Keyword arguments, passed the same way as args.
 |
 |      Example:
 |      --------
 |      >>> with webdriver.file_detector_context(UselessFileDetector):
 |      >>>    someinput.send_keys('/etc/hosts')
 |
 |  find_element(self, by='id', value: Optional[str] = None) -> selenium.webdriver.remote.webelement.WebElement
 |      Find an element given a By strategy and locator.
 |
 |      Parameters:
 |      ----------
 |      by : selenium.webdriver.common.by.By
 |          The locating strategy to use. Default is `By.ID`. Supported values include:
 |          - By.ID: Locate by element ID.
 |          - By.NAME: Locate by the `name` attribute.
 |          - By.XPATH: Locate by an XPath expression.
 |          - By.CSS_SELECTOR: Locate by a CSS selector.
 |          - By.CLASS_NAME: Locate by the `class` attribute.
 |          - By.TAG_NAME: Locate by the tag name (e.g., "input", "button").
 |          - By.LINK_TEXT: Locate a link element by its exact text.
 |          - By.PARTIAL_LINK_TEXT: Locate a link element by partial text match.
 |          - RelativeBy: Locate elements relative to a specified root element.
 |
 |      Example:
 |      --------
 |      element = driver.find_element(By.ID, 'foo')
 |
 |      Returns:
 |      -------
 |      WebElement
 |          The first matching `WebElement` found on the page.
 |
 |  find_elements(self, by='id', value: Optional[str] = None) -> List[selenium.webdriver.remote.webelement.WebElement]
 |      Find elements given a By strategy and locator.
 |
 |      Parameters:
 |      ----------
 |      by : selenium.webdriver.common.by.By
 |          The locating strategy to use. Default is `By.ID`. Supported values include:
 |          - By.ID: Locate by element ID.
 |          - By.NAME: Locate by the `name` attribute.
 |          - By.XPATH: Locate by an XPath expression.
 |          - By.CSS_SELECTOR: Locate by a CSS selector.
 |          - By.CLASS_NAME: Locate by the `class` attribute.
 |          - By.TAG_NAME: Locate by the tag name (e.g., "input", "button").
 |          - By.LINK_TEXT: Locate a link element by its exact text.
 |          - By.PARTIAL_LINK_TEXT: Locate a link element by partial text match.
 |          - RelativeBy: Locate elements relative to a specified root element.
 |
 |      Example:
 |      --------
 |      element = driver.find_element(By.ID, 'foo')
 |
 |      Returns:
 |      -------
 |      WebElement
 |          list of `WebElements` matching locator strategy found on the page.
 |
 |  forward(self) -> None
 |      Goes one step forward in the browser history.
 |
 |      Example:
 |      --------
 |      >>> driver.forward()
 |
 |  fullscreen_window(self) -> None
 |      Invokes the window manager-specific 'full screen' operation.
 |
 |      Example:
 |      --------
 |      >>> driver.fullscreen_window()
 |
 |  get(self, url: str) -> None
 |      Navigate the browser to the specified URL in the current window or
 |      tab.
 |
 |      The method does not return until the page is fully loaded (i.e. the
 |      onload event has fired).
 |
 |      Parameters:
 |      ----------
 |      url : str
 |          - The URL to be opened by the browser.
 |          - Must include the protocol (e.g., http://, https://).
 |
 |      Example:
 |      --------
 |      >>> driver = webdriver.Chrome()
 |      >>> driver.get("https://example.com")
 |
 |  get_cookie(self, name) -> Optional[Dict]
 |      Get a single cookie by name. Returns the cookie if found, None if
 |      not.
 |
 |      Example:
 |      --------
 |      >>> cookie = driver.get_cookie('my_cookie')
 |
 |  get_cookies(self) -> List[dict]
 |      Returns a set of dictionaries, corresponding to cookies visible in
 |      the current session.
 |
 |      Returns:
 |      --------
 |      cookies:List[dict] : A list of dictionaries, corresponding to cookies visible in the current
 |
 |      Example:
 |      --------
 |      >>> cookies = driver.get_cookies()
 |
 |  get_credentials(self) -> List[selenium.webdriver.common.virtual_authenticator.Credential]
 |      Returns the list of credentials owned by the authenticator.
 |
 |      Example:
 |      --------
 |      >>> credentials = driver.get_credentials()
 |
 |  get_downloadable_files(self) -> dict
 |      Retrieves the downloadable files as a map of file names and their
 |      corresponding URLs.
 |
 |      Example:
 |      --------
 |      >>> files = driver.get_downloadable_files()
 |
 |  get_log(self, log_type)
 |      Gets the log for a given log type.
 |
 |      Parameters:
 |      ----------
 |      log_type : str
 |          - Type of log that which will be returned
 |
 |      Example:
 |      --------
 |      >>> driver.get_log('browser')
 |      >>> driver.get_log('driver')
 |      >>> driver.get_log('client')
 |      >>> driver.get_log('server')
 |
 |  get_pinned_scripts(self) -> List[str]
 |      Return a list of all pinned scripts.
 |
 |      Example:
 |      --------
 |      >>> pinned_scripts = driver.get_pinned_scripts()
 |
 |  get_screenshot_as_base64(self) -> str
 |      Gets the screenshot of the current window as a base64 encoded string
 |      which is useful in embedded images in HTML.
 |
 |      Example:
 |      --------
 |      >>> driver.get_screenshot_as_base64()
 |
 |  get_screenshot_as_file(self, filename) -> bool
 |      Saves a screenshot of the current window to a PNG image file.
 |      Returns False if there is any IOError, else returns True. Use full
 |      paths in your filename.
 |
 |      Parameters:
 |      ----------
 |      filename : str
 |          - The full path you wish to save your screenshot to. This
 |          - should end with a `.png` extension.
 |
 |      Example:
 |      --------
 |      >>> driver.get_screenshot_as_file('/Screenshots/foo.png')
 |
 |  get_screenshot_as_png(self) -> bytes
 |      Gets the screenshot of the current window as a binary data.
 |
 |      Example:
 |      --------
 |      >>> driver.get_screenshot_as_png()
 |
 |  get_window_position(self, windowHandle='current') -> dict
 |      Gets the x,y position of the current window.
 |
 |      Example:
 |      --------
 |      >>> driver.get_window_position()
 |
 |  get_window_rect(self) -> dict
 |      Gets the x, y coordinates of the window as well as height and width
 |      of the current window.
 |
 |      Example:
 |      --------
 |      >>> driver.get_window_rect()
 |
 |  get_window_size(self, windowHandle: str = 'current') -> dict
 |      Gets the width and height of the current window.
 |
 |      Example:
 |      --------
 |      >>> driver.get_window_size()
 |
 |  implicitly_wait(self, time_to_wait: float) -> None
 |      Sets a sticky timeout to implicitly wait for an element to be found,
 |      or a command to complete. This method only needs to be called one time
 |      per session. To set the timeout for calls to execute_async_script, see
 |      set_script_timeout.
 |
 |      Parameters:
 |      ----------
 |      time_to_wait : float
 |          - Amount of time to wait (in seconds)
 |
 |      Example:
 |      --------
 |      >>> driver.implicitly_wait(30)
 |
 |  maximize_window(self) -> None
 |      Maximizes the current window that webdriver is using.
 |
 |      Example:
 |      --------
 |      >>> driver.maximize_window()
 |
 |  minimize_window(self) -> None
 |      Invokes the window manager-specific 'minimize' operation.
 |
 |  pin_script(self, script: str, script_key=None) -> selenium.webdriver.remote.script_key.ScriptKey
 |      Store common javascript scripts to be executed later by a unique
 |      hashable ID.
 |
 |      Example:
 |      --------
 |      >>> script = "return document.getElementById('foo').value"
 |
 |  print_page(self, print_options: Optional[selenium.webdriver.common.print_page_options.PrintOptions] = None) -> str
 |      Takes PDF of the current page.
 |
 |      The driver makes a best effort to return a PDF based on the
 |      provided Parameters.
 |
 |      Example:
 |      --------
 |      >>> driver.print_page()
 |
 |  refresh(self) -> None
 |      Refreshes the current page.
 |
 |      Example:
 |      --------
 |      >>> driver.refresh()
 |
 |  remove_all_credentials(self) -> None
 |      Removes all credentials from the authenticator.
 |
 |      Example:
 |      --------
 |      >>> driver.remove_all_credentials()
 |
 |  remove_credential(self, credential_id: Union[str, bytearray]) -> None
 |      Removes a credential from the authenticator.
 |
 |      Example:
 |      --------
 |      >>> credential_id = "user@example.com"
 |      >>> driver.remove_credential(credential_id)
 |
 |  remove_virtual_authenticator(self) -> None
 |      Removes a previously added virtual authenticator.
 |
 |      The authenticator is no longer valid after removal, so no
 |      methods may be called.
 |
 |      Example:
 |      --------

In [6]:
driver.quit()